service: aws

provider:
  name: aws
  runtime: python3.12
  region: ap-south-1
  versionFunction: false

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
